spring.application.name=camunda-app

spring.datasource.url=jdbc:postgresql://postgres:5432/camunda_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=db/changelog/changelog-master.xml
spring.liquibase.default-schema=camunda_app