# Название приложения
spring.application.name=camunda-app
# PostgreSQL — подключение к локальной БД (порт 5434)
spring.datasource.url=jdbc:postgresql://localhost:5434/camunda_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
# JPA — Hibernate не управляет схемой, миграции делает Liquibase
spring.jpa.hibernate.ddl-auto=none
# Liquibase — миграции БД, схема по умолчанию camunda_app
spring.liquibase.change-log=db/changelog/changelog-master.xml
spring.liquibase.default-schema=camunda_app
# Camunda — self-managed режим, подключение к локальному Zeebe-брокеру без авторизации
camunda.client.mode=self-managed
camunda.client.auth.method=none
camunda.client.grpc-address=http://localhost:26500
camunda.client.rest-address=http://localhost:8082
